export const MALAYSIAN_BANKS = [
    { value: "Maybank", label: "Maybank" },
    { value: "CIMB Bank", label: "CIMB Bank" },
    { value: "Public Bank", label: "Public Bank" },
    { value: "RHB Bank", label: "RHB Bank" },
    { value: "Hong Leong Bank", label: "Hong Leong Bank" },
    { value: "AmBank", label: "AmBank" },
    { value: "Bank Rakyat", label: "Bank Rakyat" },
    { value: "BSN", label: "BSN (Bank Simpanan Nasional)" },
    { value: "Bank Islam", label: "Bank Islam" },
    { value: "Affin Bank", label: "Affin Bank" },
    { value: "Alliance Bank", label: "Alliance Bank" },
    { value: "HSBC Bank Malaysia", label: "HSBC Bank Malaysia" },
    { value: "Standard Chartered Malaysia", label: "Standard Chartered Malaysia" },
    { value: "OCBC Bank Malaysia", label: "OCBC Bank Malaysia" },
    { value: "UOB Malaysia", label: "UOB Malaysia" },
    { value: "Citibank Malaysia", label: "Citibank Malaysia" },
    { value: "Bank Muamalat", label: "Bank Muamalat" },
    { value: "Bank of China Malaysia", label: "Bank of China Malaysia" },
    { value: "Kuwait Finance House", label: "Kuwait Finance House" },
    { value: "MBSB Bank", label: "MBSB Bank" },
] as const