import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClientClerkProvider } from "@/components/clerk-provider"


const inter = Inter({
    variable: "--font-inter",
    weight: ["300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Career Ladder",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClientClerkProvider>
            <html lang="en">
                <body className={`${inter.variable} antialiased font-inter`}>
                    {children}
                </body>
            </html>
        </ClientClerkProvider>
    );
}
